---
- name: Download Google Chrome
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: ./google-chrome.deb
    mode: "0600"

- name: Install Google Chrome
  changed_when: false
  ansible.builtin.command: dpkg -i google-chrome.deb
  become: true
