---
roles:
  - name: geerlingguy.docker
    version: "7.0.2"
  - name: darkwizard242.googlechrome
    version: "2.5.0"
  - name: ecgalaxy.vscode
    version: "1.3.2"
  - name: hurricanehrndz.rustup
  - name: professormanhattan.snapd
    version: "0.0.1"
  - name: Oefenweb.ssh_keys

collections:
  - ansible.posix
  - community.general
  - community.crypto
  - google.cloud
