---
- name: Execute Tasks
  hosts: localhost
  tasks:
    - name: Execute `copy-config-files` Task
      ansible.builtin.import_tasks: tasks/copy-config-files.ansible.yml
    - name: Execute `snap` Task
      ansible.builtin.import_tasks: tasks/snap.ansible.yml
    - name: Execute `obs-studio` Task
      ansible.builtin.import_tasks: tasks/obs-studio.ansible.yml
    - name: Execute `bun` Task
      ansible.builtin.import_tasks: tasks/bun.ansible.yml

- name: Execute `git` Playbook
  ansible.builtin.import_playbook: playbooks/git.ansible.yml
- name: Execute `starship` Playbook
  ansible.builtin.import_playbook: playbooks/starship.ansible.yml
# - name: Execute `playbooks/atuin.ansible.yml`
#   ansible.builtin.include_tasks: playbooks/atuin.ansible.yml
