---
- name: Run setups
  hosts: all
  tasks:
    - name: Execute each setup task
      ansible.builtin.import_tasks: "{{ item }}" 
      with_items:
        - playbooks/copy-config-files.andrew.yml
        - playbooks/git.ansible.yml
        - playbooks/bun.ansible.yml
        - playbooks/snap.ansible.yml
        - playbooks/obs-studio.ansible.yml
        - playbooks/starship.ansible.yml
        # - playbooks/atuin.ansible.yml
