---
- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
    mode: "0600"
  with_items:
    - .gitconfig
    - starship.toml
    - .bashrc
    - .bash_aliases
  become: true
