---
- name: Setup Snap Packages
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install Discord and Spotify
      community.general.snap:
        name:
          - discord
          - spotify
