"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[hostname]
format = "[ 󰒋 $hostname]($style) at "
ssh_only = false

[character]
success_symbol = "[ 󱞪](bold green)"
error_symbol = "[ 󱞪](bold red)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_symbol = "[](bold green)"
vimcmd_visual_symbol = "[](bold yellow)"

[package]
disabled = true
