---
- name: Setup Git
  hosts: all
  vars_prompt:
    - name: git_personal_username
      prompt: "Enter your personal username for Git"
      private: true
    - name: git_personal_email
      prompt: "Enter your personal email address for Git"
      private: true
    - name: git_work_username
      prompt: "Enter your work username for Git"
      private: true
    - name: git_work_email
      prompt: "Enter your work email address for Git"
      private: true
  tasks:
    - name: Install git-core and git-flow
      become: true
      ansible.builtin.apt:
        pkg:
          - git-core
          - git-flow
    - name: Configure "set-personal-account" Git alias
      community.general.git_config:
        name: alias.set-personal-account
        value: "!git config user.name \"{{ git_personal_username }}\" && git config user.email \"{{ git_personal_email }}\""
    - name: Configure "set-work-account" Git alias
      community.general.git_config:
        name: alias.set-work-account
        value: "!git config user.name \"{{ git_work_username }}\" && git config user.email \"{{ git_work_email }}\""
